version: '3.8'
services:
  api-service:
    build: .
    volumes:
      - .:/app
      - ${GCP_KEY_PATH}:/secrets/gcp-key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-key.json
      - COG_STORAGE_URL=${COG_STORAGE_URL}
      - PYTHONAPP=/app
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8080 --reload
